config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todos_path, notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy!

    respond_to do |format|
      format.html { redirect_to todos_path, status: :see_other, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test Proj 1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= hotwire_livereload_tags if Rails.env.development? %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 max-w-[500px]">
      <%= yield %>
    </main>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_area :title, class: "w-full rounded-lg" %>
  </div>

  <div>
    <%= form.label :completed, style: "display: block" %>
    <%= form.select :completed,
                    options_for_select(
                      [['Not Complete', 0],
                       ['Complete', 1]],
                      selected: todo.completed,
                    ),
                    {},
                    { class: "w-full rounded-lg" }
    %>
  </div>
  <h1>
  </h1>
  <div class="mt-8">
    <%= form.submit class: "bg-blue-500 text-white cursor-pointer px-4 py-2 rounded-full mt-2" %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>" xmlns="http://www.w3.org/1999/html">
  <p>
    <strong>Title:</strong>
    <%= todo.title %>
  </p>

  <p>
    <strong>Completed:</strong>
    <span class="<%= todo.completed == 1 ? 'text-green-700' : 'text-red-700' %>">
    <%= todo.completed == 1 ? "Completed" : "Not Completed" %>
    </span>
  </p>

</div>

app/views/todos/edit.html.erb
<% content_for :title, "Editing todo" %>

<div class="flex flex-col">
  <h1 class="text-4xl font-bold mb-4">Editing Todo</h1>
  <hr class="mb-8"/>

  <div class="w-full">
    <%= render "form", todo: @todo %>
  </div>

  <br>

  <div>
    <%= link_to "Show this todo", @todo %> |
    <%= link_to "Back to todos", todos_path %>
  </div>
</div>

app/views/todos/index.html.erb
<% content_for :title, "Todos" %>

<header class="w-full flex justify-between mb-4">
  <h1 class="text-4xl font-bold">Todos</h1>
  <%= link_to new_todo_path,
              class: "flex items-center gap-1 text-blue-500 hover:text-blue-600 hover:underline hover:underline-offset-2 transition-all" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 448 512" fill="currentColor" title="Add todo">
      <path d="M256 80c0-17.7-14.3-32-32-32s-32 14.3-32 32l0 144L48 224c-17.7 0-32 14.3-32 32s14.3 32 32 32l144 0 0 144c0 17.7 14.3 32 32 32s32-14.3 32-32l0-144 144 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-144 0 0-144z"/>
    </svg>
    New Todo
  <% end %>
</header>

<input id="search" name="search" placeholder="Search by title" type="text"/>

<hr class="mb-8"/>

<p class="text-green-700 mb-4"><%= notice %></p>

<div id="todos" class="grid grid grid-cols-3 gap-4">
  <% @todos.each do |todo| %>
    <div class="flex flex-col gap-2 bg-gray-50 px-4 py-4 rounded-lg border border-gray-300">
      <%= render todo %>
      <div class="flex gap-4 self-end items-baseline">
        <%= link_to edit_todo_path(todo), class: "cursor-pointer" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 512 512" fill="currentColor" title="Edit todo">
            <path d="M362.7 19.3L314.3 67.7 444.3 197.7l48.4-48.4c25-25 25-65.5 0-90.5L453.3 19.3c-25-25-65.5-25-90.5 0zm-71 71L58.6 323.5c-10.4 10.4-18 23.3-22.2 37.4L1 481.2C-1.5 489.7 .8 498.8 7 505s15.3 8.5 23.7 6.1l120.3-35.4c14.1-4.2 27-11.8 37.4-22.2L421.7 220.3 291.7 90.3z"/>
          </svg>
        <% end %>
        <%= button_to todo, method: :delete, class: "cursor-pointer" do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 448 512" fill="currentColor" title="Delete todo">
            <path d="M135.2 17.7L128 32 32 32C14.3 32 0 46.3 0 64S14.3 96 32 96l384 0c17.7 0 32-14.3 32-32s-14.3-32-32-32l-96 0-7.2-14.3C307.4 6.8 296.3 0 284.2 0L163.8 0c-12.1 0-23.2 6.8-28.6 17.7zM416 128L32 128 53.2 467c1.6 25.3 22.6 45 47.9 45l245.8 0c25.3 0 46.3-19.7 47.9-45L416 128z"/>
          </svg>
        </button>
      </form>
    </div>
  </div>
  `;
            todosContainer.innerHTML += todoHtml;
        });
    }

    document.addEventListener('DOMContentLoaded', renderTodos);

    console.log(document.getElementById("search"));
    document.getElementById("search").addEventListener("keyup", function () {
        search = this.value;
        renderTodos();
    });
</script>

app/views/todos/new.html.erb
<% content_for :title, "New todo" %>

<div class="flex flex-col">
  <h1 class="text-4xl font-bold mb-4">Create a New Todo</h1>
  <hr class="mb-8"/>

  <div class="w-full mb-6">
    <%= render "form", todo: @todo %>
  </div>

  <%= link_to "Back to todos",
              todos_path,
              class: "text-blue-500 hover:text-blue-600 hover:underline hover:underline-offset-2 transition-all mb-4" %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>